=== surajgaire14/lab-web-ncit/lab-xml/Q5/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Subjects">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subject" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="topics">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="topic1" type="xs:string" />
                                        <xs:element name="topic2" type="xs:string" />
                                        <xs:element name="topic3" type="xs:string" />
                                        <xs:element name="topic4" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== surajgaire14/lab-web-ncit/lab-xml/Q5/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./index.xsl" type="text/xsl" ?>

<Subjects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
    <subject>
        <name>Algo</name>
        <topics>
            <topic1>Greedy Algo</topic1>
            <topic2>Randomized Algo</topic2>
            <topic3>Searching Algo</topic3>
            <topic4>Sorting Algo</topic4>
        </topics>
    </subject>
    <subject>
        <name>Data Structures</name>
        <topics>
            <topic1>Array </topic1>
            <topic2>Stack</topic2>
            <topic3>Queue</topic3>
            <topic4>Linked List</topic4>
        </topics>
    </subject>
    <subject>
        <name>Web Technology</name>
        <topics>
            <topic1>HTML</topic1>
            <topic2>CSS</topic2>
            <topic3>JAVASCRIPT</topic3>
            <topic4>Php</topic4>
        </topics>
    </subject>
    <subject>
        <name>Languages</name>
        <topics>
            <topic1>C/C++</topic1>
            <topic2>Java</topic2>
            <topic3>Python</topic3>
            <topic4>Ruby</topic4>
        </topics>
    </subject>
    <subject>
        <name>DBMS</name>
        <topics>
            <topic1>Basics</topic1>
            <topic2>E/R Diagram</topic2>
            <topic3>Normalization</topic3>
            <topic4>Transaction Concepts</topic4>
        </topics>
    </subject>
</Subjects>
